**Task-2**: Apply algorithm on digits dataset - One hot encoding of features and train test division 65% - 35%

In [1]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

In [2]:
#Load dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [3]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [4]:
#import the necessary module
from sklearn.model_selection import train_test_split

X=digits.data
Y=digits.target
#split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.35, random_state = 46)

In [7]:
#Create a Decision Tree Classifier (using Gini)
clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 46,max_depth=7, min_samples_leaf=46)

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=46, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=46, splitter='best')

In [12]:
# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[6 1 1 6 1 2 9 5 1 3 9 7 5 7 3 7 1 0 7 9 3 9 2 2 4 8 9 4 6 1 4 5 9 8 4 7 9
 8 1 8 0 3 7 0 9 2 3 3 7 6 1 7 9 9 4 6 2 9 9 5 7 1 9 6 6 6 4 2 7 2 5 7 9 5
 6 1 9 4 6 7 1 7 0 4 7 1 7 2 6 1 9 9 0 7 7 7 6 0 8 9 6 3 7 2 6 1 9 9 9 5 3
 5 3 1 8 3 9 9 6 9 9 7 1 3 9 7 2 3 7 3 9 5 2 8 7 0 5 7 2 6 3 6 7 4 6 6 0 6
 8 8 9 1 1 2 7 5 0 1 9 5 9 6 9 9 0 0 1 8 2 1 2 7 3 3 9 9 7 1 1 1 6 6 1 8 9
 5 2 7 5 9 9 3 6 9 4 4 1 9 6 1 4 1 5 7 3 8 6 2 1 3 7 7 3 6 5 0 3 1 1 7 4 9
 5 8 4 0 1 3 7 9 4 7 4 9 5 9 3 9 4 3 7 9 6 3 1 0 9 2 8 1 3 9 8 4 8 9 0 6 5
 2 0 9 2 3 5 1 0 5 7 9 6 1 9 1 3 9 0 1 8 6 4 2 0 7 6 1 7 9 7 9 1 6 3 7 3 1
 5 0 7 7 7 7 7 3 6 5 0 0 7 6 2 0 1 7 3 4 4 2 2 1 6 1 7 3 5 0 7 6 5 2 2 7 8
 1 7 9 4 1 9 9 6 9 1 5 6 6 3 3 0 1 1 1 4 2 6 3 3 1 7 3 2 1 8 1 2 1 3 5 1 6
 9 9 6 2 2 6 9 7 0 1 7 2 3 5 9 2 9 0 8 9 3 8 5 3 2 1 0 7 2 0 0 2 1 9 4 8 3
 4 9 7 5 4 8 0 6 6 3 9 5 8 1 7 9 1 1 1 2 7 7 9 1 1 1 7 9 9 4 1 0 9 2 9 9 8
 7 7 0 9 7 2 8 0 1 3 8 0 6 0 6 5 6 7 4 2 7 3 2 9 3 2 9 1 1 7 9 6 4 9 3 9 9
 4 6 9 

In [13]:
# Model Accuracy
from sklearn import metrics
print("Confusion Matrix: ",
        metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy : ",
    metrics.accuracy_score(y_test,y_pred)*100)
print("Report : ",
    metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[42  0  0  0  0  0  0  0  0  2]
 [ 0 37  1  1  8  0  6  3  1  9]
 [ 1 20 37  5  1  0  5  1  2  1]
 [ 0  7  0 49  0  0  0  4  1  5]
 [ 4  3  1  0 36  0  8  9  1  0]
 [ 4  5  0  0  1 43  2  2  0 12]
 [ 0  3  0  0  0  0 49  0  0  0]
 [ 0  0  7  0  1  0  0 55  1  3]
 [ 0  8  2  5  0  0  0  4 26 12]
 [ 0  0  1  4  0  0  0  7  1 60]]
Accuracy :  68.99841017488076
Report :                precision    recall  f1-score   support

           0       0.82      0.95      0.88        44
           1       0.45      0.56      0.50        66
           2       0.76      0.51      0.61        73
           3       0.77      0.74      0.75        66
           4       0.77      0.58      0.66        62
           5       1.00      0.62      0.77        69
           6       0.70      0.94      0.80        52
           7       0.65      0.82      0.72        67
           8       0.79      0.46      0.58        57
           9       0.58      0.82      0.68        73

    accuracy  